### PR TITLE
Add a Binder badge to the README

### PR DESCRIPTION
**Pull request by jtpio**
No extra files required, as `repo2docker` can use the existing `setup.py`.

### CODE REVIEW

**Comment by jtpio** [comment]
We could add the extra files to be able to pin on specific PyPI releases though.

**Comment by fcollonval** [comment]
Done in ab7fa88

**Comment by vidartf** [comment]
It would be nice if we kept doing changes via PRs though :-/

**Comment by fcollonval** [comment]
> It would be nice if we kept doing changes via PRs though :-/

Sorry for that @vidartf I was definitely too quick on that one.

**Pull request closed without merging**
